add playlist class interface
Guptacos/spotifython pull request #17
Opened 2020-04-28 06:58 UTC by rmannava

2020-05-02 17:42 UTC, adithyaraghuraman98 commented on spotifython/playlist.py
> +        playlist_info['owner'] = User(playlist_info['owner'])
Why are you updating the playlist_info variable, shouldn't you be updating self._raw?

2020-05-02 17:44 UTC, adithyaraghuraman98 commented on spotifython/playlist.py
> +            item['track'] = Track(item['track'])
Same here.

2020-05-02 17:46 UTC, adithyaraghuraman98 reviewed
Had a minor question in playlist.py

2020-05-02 20:20 UTC, eyluo requested changes

2020-05-02 20:20 UTC, eyluo commented on spotifython/playlist.py
> +        playlist_info['owner'] = User(playlist_info['owner'])
> Why are you updating the playlist_info variable, shouldn't you be updating self._raw?

On the one hand, this defensive copying means that a nasty user wouldn't be able to break code by passing in a `dict` and then modifying it, thus borking the rest of the object.

On the other hand, Python is a language for "consenting adults." Furthermore, the constructors are "hidden" from the user, so they shouldn't be making their own `Playlist` objects explicitly.

Either one works for me. I'm defensively copying on my branch. ¯\_(ツ)_/¯

2020-05-02 20:20 UTC, eyluo commented on spotifython/playlist.py
> +            item['track'] = Track(item['track'])
> Same here.

Agree: I think you should put this into a `self._tracks : Track` list.

2020-05-02 20:20 UTC, eyluo commented on spotifython/playlist.py
> +        for item in playlist_info['tracks']['items']:
We should be wary of partial inputs. This loop should change to something like:
```python3
tracks = playlist_info.get('tracks', {})
if tracks != None:
    for item in tracks.get('items', []):
        ...
```

2020-05-02 20:20 UTC, eyluo commented on spotifython/playlist.py
> +    def add_tracks(self, track, position=None):
For consistency, I think we should use the `typing` module to annotate function declarations.

```python3
def add_tracks(self, track : Union[Track, List[Track]], position=None):
    ...
```

2020-05-02 20:20 UTC, eyluo commented on spotifython/playlist.py
> +        tracks:   A list of Track objects to be added.
Support both singleton and list of `Track`

2020-05-02 20:20 UTC, eyluo commented on spotifython/playlist.py
> +        position: An integer specifying the 0-indexed position in the playlist
Does Spotify's API make any comment about illegal positions? Negative, too large for playlist, etc.

2020-05-02 20:20 UTC, eyluo commented on spotifython/playlist.py
> +        Parameters:
Are the only options collaborative, public, and private? If so, it might be worth doing method cleavage and erroring out if they try to make a collaborative playlist public.

2020-05-02 20:20 UTC, eyluo commented on spotifython/playlist.py
> +    def image(self):
The response object could potentially give you 3 differently-sized images in a list. I think you should default to the largest (first item in the list) and optionally give different sizes? Even I'm skeptical about the last part, but just keep in mind how the API behaves.

2020-05-02 20:20 UTC, eyluo commented on spotifython/playlist.py
> +        start:      An integer specifying the 0-indexed position of the first
what happens if start is negative or too big?

2020-05-02 20:20 UTC, eyluo commented on spotifython/playlist.py
> +        positions: A list of integers specifying the 0-indexed positions of
what happens if position is negative or too big?

2020-05-02 20:20 UTC, eyluo commented on spotifython/playlist.py
> +        number:            A nonnegative integer specifying the number of tracks to
same as above

2020-05-03 02:27 UTC, eyluo approved these changes

2020-05-03 02:28 UTC, merged