first pass at impl of request
Guptacos/spotifython pull request #30
Opened 2020-05-04 03:03 UTC by spenceryu

2020-05-04 21:03 UTC, rmannava commented on spotifython/Spotifython.py
> +            the request is executed, and (None, TypeError) if the request type is invalid.
should it just raise an exception and in that case we know theres no response json or status code?

2020-05-04 21:11 UTC, rmannava requested changes

2020-05-04 21:11 UTC, rmannava commented on spotifython/Spotifython.py
> +        headers = {'Authorization': self._token}
should be "Authorization: Bearer " + self._token

2020-05-04 21:38 UTC, spenceryu commented on spotifython/Spotifython.py
> +            the request is executed, and (None, TypeError) if the request type is invalid.
We should discuss this over a meeting.

2020-05-05 01:02 UTC, adithyaraghuraman98 approved these changes

2020-05-05 01:02 UTC, rmannava approved these changes

2020-05-05 01:02 UTC, merged