Artist impl
Guptacos/spotifython pull request #31
Opened 2020-05-05 07:16 UTC by spenceryu

2020-05-05 15:16 UTC, Guptacos requested changes

2020-05-05 15:16 UTC, Guptacos commented on spotifython/artist.py
> +        self.albums = None
underscore private fields

2020-05-05 15:16 UTC, Guptacos commented on spotifython/artist.py
> +        if 'genres' not in self._raw: self._update_fields()
Need to do extra check on all these returns. What if (for some reason) _update_fields fails to update the field you're returning?

2020-05-05 15:16 UTC, Guptacos commented on spotifython/artist.py
> +        self.albums = self.albums if self.albums is not None and \
Break this up into an if / else. If the one liner is long enough it needs a '\', should probably be separated for readability

2020-05-05 15:16 UTC, Guptacos commented on spotifython/artist.py
> +        if (search_limit is not None and not isinstance(search_limit, int)):
None not an instance of int or string

2020-05-05 15:16 UTC, Guptacos commented on spotifython/artist.py
> +        self.top_tracks = self.top_tracks if self.top_tracks is not None and \
same here, break it up

2020-05-05 15:16 UTC, Guptacos commented on spotifython/artist.py
> +        if (market is not None):
Can't be None, you raise ValueError on line 213

2020-05-25 06:10 UTC, spenceryu commented on spotifython/artist.py
> +        if (search_limit is not None and not isinstance(search_limit, int)):
I meant to make it like an Optional in Java, but forcing it to be required (with a default value) is probably cleaner.

2020-05-31 14:30 UTC, Guptacos requested changes

2020-05-31 14:30 UTC, Guptacos commented on spotifython/album.py
> -from track import Track
Artist class PR shouldn't modify album, remove from commit

2020-05-31 14:30 UTC, Guptacos commented on spotifython/endpoints.py
> +    ARTIST_GET_ALBUMS = '/v1/artists/{}/albums'
Prefix endpoints with a comment breaking it into an artist section

2020-05-31 14:30 UTC, Guptacos commented on spotifython/player.py
> -from album import Album
Artist class PR shouldn't modify player, remove from commit

2020-05-31 14:30 UTC, Guptacos commented on spotifython/playlist.py
> -from user import User
Artist class PR shouldn't modify playlist, remove from commit

2020-05-31 14:30 UTC, Guptacos commented on spotifython/track.py
>  from copy import deepcopy
Artist class PR shouldn't modify track, remove from commit

2020-05-31 14:30 UTC, Guptacos commented on spotifython/user.py
> -from album import Album
Artist class PR shouldn't modify user, remove from commit

2020-05-31 14:30 UTC, Guptacos commented on spotifython/session.py
> +
Are these changes different than those present in your Session PR? If not, remove them from this PR so as not to create conflicts

2020-05-31 14:30 UTC, Guptacos commented on spotifython/artist.py
> +Album = Any  # album.py imports this module.
Why do you need these 3 lines

2020-05-31 14:30 UTC, Guptacos commented on spotifython/artist.py
> +        response_json, _ = utils.request(
Probably shouldn't ignore the return code

2020-05-31 14:30 UTC, Guptacos commented on spotifython/artist.py
> +        self._raw = {**self._raw, **response_json}
I feel like we should make this a helper function in utils since so many classes do this weird notation. Just a TODO for the future

2020-05-31 14:30 UTC, Guptacos commented on spotifython/artist.py
> +            N/A
Change to `None`

Does this really not need any scopes?

2020-06-01 03:00 UTC, spenceryu commented on spotifython/artist.py
> +            N/A
yes, see https://developer.spotify.com/documentation/web-api/reference/artists/get-artists-albums/

2020-06-01 12:48 UTC, Guptacos requested changes

2020-06-01 12:48 UTC, Guptacos commented on spotifython/artist.py
> +        endpoint = f'/v1/artists/{self.spotify_id()}'
endpoints should be stored in the endpoints.py file

2020-06-01 12:48 UTC, Guptacos commented on spotifython/artist.py
> +# pylint: disable = too-many-branches, wrong-import-position
You shouldn't need wrong-import-position since this file isn't importing any of the other classes

2020-06-03 13:20 UTC, Guptacos requested changes

2020-06-03 13:20 UTC, Guptacos commented on spotifython/artist.py
> +        self.session = session
This should be _session

2020-06-07 02:14 UTC, rmannava commented on spotifython/artist.py
> +    def __init__(self, session, artist_info):
call it just info?

2020-06-07 02:14 UTC, rmannava commented on spotifython/utils.py
> +    raise SpotifyError if the field is still invalid post-update.
The first sentence should be separated by an empty line

2020-06-07 02:14 UTC, rmannava commented on spotifython/utils.py
> +    SpotifyError.
first line spacing

2020-06-07 12:54 UTC, Guptacos commented on spotifython/utils.py
> +    raise SpotifyError if the field is still invalid post-update.
+1 on this

2020-06-07 12:54 UTC, Guptacos commented on spotifython/utils.py
> +    SpotifyError.
+1

2020-06-07 12:55 UTC, Guptacos commented on spotifython/artist.py
> +    def __init__(self, session, artist_info):
+1 we should be consistent in all our files

2020-06-08 15:38 UTC, Guptacos approved these changes

2020-06-08 15:39 UTC, merged