Top impl
Guptacos/spotifython pull request #32
Opened 2020-05-05 08:05 UTC by spenceryu

Still need to write testing code - just a WIP if you want to provide feedback.
TODO: 
- Update response type hinting and documentation to not be of type Response, instead returning desired type or throwing exception otherwise.
- Define responses in the case of partial failures

2020-05-05 15:02 UTC, Guptacos requested changes

2020-05-05 15:02 UTC, Guptacos commented on spotifython/Spotifython.py
> +        # Encode the spaces in strings! See 'Search -> Writing a Query - Guidelines'
Provide a link instead of telling how to get there

2020-05-05 15:02 UTC, Guptacos commented on spotifython/Spotifython.py
> +        remaining_search_types = [s + 's' for s in search_types]
These are enums, not constants, so we shouldn't rely on their value. Better to have a private dict mapping enum->value

2020-05-05 15:02 UTC, Guptacos commented on spotifython/Spotifython.py
> +    SEARCH_RESPONSE_TYPE_ALBUM = 'albums'
Why do you need SEARCH_RESPONSE_TYPE_ALBUM when we already have ALBUM?

2020-05-05 15:02 UTC, Guptacos commented on spotifython/Spotifython.py
> +                if (t is self.SEARCH_RESPONSE_TYPE_ALBUM):
Instead of having 4 methods in SearchResult, and then having 4 if statements each time to pick a method, consolidate SearchResult to have 1 _add method.

This _add method should check the type and add it to the appropriate internal thing. SearchResult ends up being the same length, but 284 - 291 becomes 1 method call

2020-05-05 15:02 UTC, Guptacos commented on spotifython/Spotifython.py
> +        if (market is not None and not isinstance(market, str)):
combine 339-345. isinstance(None, str) => False

2020-05-05 15:02 UTC, Guptacos commented on spotifython/endpoint.py
> +    SERACH_GET_USER = '/v1/users/{}'
typo serach

2020-05-25 06:33 UTC, spenceryu commented on spotifython/Spotifython.py
> +    SEARCH_RESPONSE_TYPE_ALBUM = 'albums'
I made a mistake when filling out the parameters. The order is a little different now that we have renamed the constants in the enums as the plural version. As per the search documentation, the valid params are of the singular variety.
- `Valid types are: album , artist, playlist, track, show and episode.`

2020-05-31 14:16 UTC, Guptacos requested changes

2020-05-31 14:16 UTC, Guptacos commented on README.md
> +
delete newline for linter

2020-05-31 14:16 UTC, Guptacos commented on spotifython/album.py
> -from track import Track
Session class PR shouldn't modify album, remove from commit

2020-05-31 14:16 UTC, Guptacos commented on spotifython/endpoints.py
> -# endpoint.BASE_URI
Add comment prefixing the search constants

2020-05-31 14:16 UTC, Guptacos commented on spotifython/player.py
> -from artist import Artist
Session class PR shouldn't modify player, remove from commit

2020-05-31 14:16 UTC, Guptacos commented on spotifython/playlist.py
> -from track import Track
Session class PR shouldn't modify playlist, remove from commit

2020-05-31 14:16 UTC, Guptacos commented on spotifython/track.py
> -from artist import Artist
Session class PR shouldn't modify track, remove from commit

2020-05-31 14:16 UTC, Guptacos commented on spotifython/user.py
> -from album import Album
Session class PR shouldn't modify user, remove from commit

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +# Aliases to avoid circular dependencies
Why do you need lines 18-22?

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +# pylint: disable=pointless-string-statement, too-many-instance-attributes
These linter disables should be used on a case by case basis, not at the top of the file

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +            raise TypeError(timeout)
What if timeout is some whacky value like negative? Should it raise ValueError

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
>      def token(self):
Change the "Returns a str" to use google docstring conventions

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> -        ''' Getter for the timeout provided by the client
same as above for returns

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +        return self._token == other._token
Users shouldn't have multiple sessions, I think it's reasonable to remove __eq__ and __ne__

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +        return hash(self.token)
Bad way to hash; if the user reauthenticates the object hash changes

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +        return hash(self.token)
See above comment on removing __eq__ and __ne__, I think we should just remove hash for Session

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +                search_info: dictionary, contains known values about the user
about the user?

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +            if isinstance(iterable, List[Album]):
Pretty sure this type of check doesn't work

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +            if isinstance(iterable, List[Album]):
You also aliased `Album`, `Artist`, etc. to `Any`, so everything will get added to self._add_albums

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +        def _add_albums(self, albums):
These 4 functions can be combined

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +            query: str, search query keywords and optional field filters and
Change all instances of `const.` in documentation to `sp.`, since clients will access the constants using `sp.`

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +        type_mapping = {
Instead of defining const.SEARCH_TYPE* for each of these, maybe worthwhile to just put the strings here since they're only used locally?

i.e. `const.ALBUMS: 'album'`

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +                if response_json[curr_type]['next'] != 'null':
What happens if you don't update remaining types? Will it just keep returning 'null' for the types that are exhausted, or will something worse happen?

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +        if not isinstance(album_ids, Union[str, List[str]]):
Again, I don't think these types of checks work

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +            # Execute requests
Why ignore the return code?

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +            uri_params['ids'] = ','.join(batch)
does request() not automatically join them? I thought you can pass it a list

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +    def get_artists(self,
Same feedback for rest of get_ functions as get_albums

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +                raise ValueError('Spotify API key is not valid')
request() handles auth errors

2020-05-31 14:16 UTC, Guptacos commented on spotifython/session.py
> +            raise ValueError(response_json)
This ValueError won't be useful to the caller, since it'll say `ValueError(None)`

2020-05-31 14:23 UTC, Guptacos requested changes

2020-05-31 14:23 UTC, Guptacos commented on spotifython/session.py
> +# pylint: disable=pointless-string-statement, too-many-instance-attributes
If there are a lot of cases where you need to put the linter exception, it may be better to refactor the code a little

2020-06-01 01:16 UTC, spenceryu commented on README.md
> +
The linter doesn't exist for non-.py files right? Are we doing one newline at end of file?

2020-06-01 01:18 UTC, spenceryu commented on spotifython/session.py
> +# Aliases to avoid circular dependencies
http://google.github.io/styleguide/pyguide.html#31914-circular-dependencies
I was following this, but our hacky solution of importing at the end probably doesn't require it.

2020-06-01 02:16 UTC, spenceryu commented on spotifython/session.py
> +                if response_json[curr_type]['next'] != 'null':
unsure. probably just unnecessary API calls, but this is something to verify in testing the live API.

2020-06-01 02:24 UTC, spenceryu commented on spotifython/session.py
> +            uri_params['ids'] = ','.join(batch)
utils.request() does not fulfill the purpose requested due to the limit of 20 albums being returned per call. This can be a nested list of batches. For example, someone can pass in 100 album_ids and it will separate this into five comma-joined lists for five requests.

2020-06-01 13:09 UTC, Guptacos requested changes

2020-06-01 13:09 UTC, Guptacos commented on spotifython/session.py
> +# pylint: disable=undefined-variable
Remove lines 16-17
move the `wrong-import-position` to the end of the file

To fix the problem, add the imports at the bottom of the file. I.e.

```python
#pylint: disable=wrong-import-position
from spotifython.album import Album
from spotifython.artist import Artist
from spotifython.playlist import Playlist
from spotifython.track import Track
from spotifython.user import User
```

2020-06-01 13:09 UTC, Guptacos commented on spotifython/session.py
> +                if response_json[curr_type]['next'] != 'null':
Okay, TODO for the future then

2020-06-01 13:09 UTC, Guptacos commented on spotifython/session.py
> +            uri_params['ids'] = ','.join(batch)
What I meant is that in utils.request, it calls requests.request with uri_params, which is a dict of params to format into a url string. I'm pretty sure that if you give it a list of values, it effectively calls `','.join()`, so you don't need to

2020-06-01 13:09 UTC, Guptacos commented on spotifython/session.py
> +        def __init__(self, search_info):
This is only ever called with an empty dict; easier to just remove that param and hardcode initialization.

2020-06-01 13:09 UTC, Guptacos commented on spotifython/session.py
> +# pylint: disable=wrong-import-position, protected-access
Should remove the pylint ignore protected-access, see below for how to fix

2020-06-01 13:09 UTC, Guptacos commented on spotifython/session.py
> +        result = self.SearchResult(dict())
Note this is the only place you construct a SearchResult

2020-06-01 13:09 UTC, Guptacos commented on spotifython/session.py
> +                result._add(acc)
This is the only place that pylint complains about a protected access. Instead of muting the protected access, you can make minor changes so that it's a legal access.

For example, you could change result from a SearchResult to a list, then append to the list. Once the list is built up, at the end of the function, you return SearchResult(result_list). Since SearchResult no longer needs an info dict in the constructor (see earlier comment), it can instead take this result_list, and in the constructor call self._add() for each item in result_list.

This barely changes the Search code, but makes the SearchResult code more readable and eliminates the need for protected access

2020-06-05 15:05 UTC, Guptacos requested changes

2020-06-05 15:05 UTC, Guptacos commented on spotifython/session.py
> +            result.append(User(response_json))
All constructors take in (session, info)

2020-06-05 15:05 UTC, Guptacos commented on spotifython/session.py
> +        return User(response_json)
Same here, constructor needs session obj

2020-06-05 15:05 UTC, Guptacos commented on spotifython/session.py
> +    def get_current_user(self):
Just a thought, should this maybe be named current_user? We should discuss

2020-06-06 19:45 UTC, spenceryu commented on spotifython/session.py
> +            uri_params['ids'] = ','.join(batch)
I'll take your suggestion for now and make sure it works by testing on the live API.

2020-06-06 20:00 UTC, spenceryu commented on spotifython/session.py
> +                result._add(acc)
Please see the new changes to the class. It now takes in a dictionary, but is just used for convenient getters. The logic is all done using a dictionary of lists in the search function instead.

2020-06-07 02:17 UTC, rmannava submitted a review, later dismissed

2020-06-07 12:51 UTC, Guptacos requested changes

2020-06-07 12:51 UTC, Guptacos commented on spotifython/session.py
> +    def get_current_user(self):
Change to current_user() like we discussed

2020-06-07 12:51 UTC, Guptacos commented on spotifython/session.py
> +    def get_current_user(self):
If renaming the method might need to also rename something in the test file?

2020-06-08 15:36 UTC, Guptacos submitted a review, later dismissed

2020-06-08 15:41 UTC, Guptacos approved these changes

2020-06-08 15:42 UTC, merged