Playlist implementation
Guptacos/spotifython pull request #67
Opened 2020-06-01 00:36 UTC by rmannava

pending unit tests and dunder methods

2020-06-01 01:13 UTC, spenceryu requested changes

2020-06-01 01:13 UTC, spenceryu commented on spotifython/endpoints.py
> +    PLAYLIST = '/v1/playlists/{playlist_id}'
Update endpoint formatting convention

2020-06-01 01:13 UTC, spenceryu commented on spotifython/playlist.py
> +        response_json, status_code = utils.request(self._session, 'POST',
use named params, makes it easier to debug if you skipped one or we refactor it later

2020-06-01 01:13 UTC, spenceryu commented on spotifython/playlist.py
> +        Args:
Please update your arguments to follow new style guidelines - we are including required scopes and endpoint URI that this function targets.

2020-06-01 01:27 UTC, Guptacos requested changes

2020-06-01 01:27 UTC, Guptacos commented on spotifython/endpoints.py
> +    PLAYLIST = '/v1/playlists/{playlist_id}'
Change to %s format

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        """ Playlist constructor that should never be called directly.
By the client

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        self._owner = User(session, info.get('owner', {}))
User raises an exception if `id` not in info. This call should probably raise its own exception instead of passing  in an empty dict

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        tracks = info.get('tracks', {})
`if tracks` will always pass (I think?), should check `if len(tracks) == 0`

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
>                  self._tracks.append(Track(item.get('track', {})))
Same as with user constructor, shouldn’t pass in an empty dict. Either populate the track or raise an exception

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        return deepcopy(self._owner)
Only use deepcopy on input info list in constructor. After that, probably not necessary

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +            position: An integer specifying the 0-indexed position in the
Are there any restrictions on the value of position?

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        endpoint = Endpoints.BASE_URI
Should validate inputs; confirm all items in track are Track objects and that position has the correct value

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST.replace('{playlist_id}', self._raw['id'])
Use % formatting for endpoints

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST.replace('{playlist_id}', self._raw['id'])
% formatting

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        if visibility == const.PUBLIC:
Can consolidate the code a lot:
```
if visibility not in [const.PUBLIC, const.PRIVATE, const.PRIVATE_COLLAB]:
    raise ValueError(visibility)
body['public'] = visibility == const.PUBLIC
body['collaborative'] = visibility == const.PRIVATE_COLLAB
```

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST_IMAGES.replace('{playlist_id}',
% formatting

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +            start: An integer specifying the 0-indexed position of the first
Any restriction on either of these? what if `num_tracks > len(playlist)` or `start > len(playlist)`

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
>          given position. Returns all of the tracks in the playlist when given no
What do you mean given no paramaters? Maybe say "use the default values to get all tracks"

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST_TRACKS.replace('{playlist_id}',
% formatting

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        if not num_tracks:
Should validate inputs

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
>          parameters are provided, positions takes precedence.
This sounds like too much of a transliteration of the REST api. If both (or neither) params are provided, it's probably a programmer error, and should raise an exception.

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +            positions: An integer or list of integers specifying the 0-indexed
Any restrictions? What if a track in `tracks` is not in the playlist? What if the positions are negative or greater than the length of the playlist?

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST_TRACKS.replace('{playlist_id}',
% formatting

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        if tracks and not positions:
While it's idiomatic in C to do `if var` for NULL checks, in Python it's conventional to do `if tracks is not None and positions is None`

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        elif positions:
Same here `positions is not None`

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +            if not tracks:
`if tracks is None`

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        else:
Hides programmer error, should raise exception

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
>      def reorder_tracks(self, source_index, destination_index, number=1):
maybe rename source_index and destination index? I feel like destination_index could at least be renamed to dest_index, which is convention

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
>          Moves the specified number of tracks starting at source_index to before
Change to use variable names for clarity:
"Move 'number' tracks from 'source_index' to 'destination_index'"

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +            source_index: An integer specifying the 0-indexed position of the
what is a "valid index"?

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +            number: A nonnegative integer specifying the number of tracks to be
0 should raise an exception, probably programmer error

What if number > len(playlist)?

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST_TRACKS.replace('{playlist_id}',
% formatting

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        if (source_index < 0 or
Can move these checks to the top so that you don't need the 2 extra variables

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +                             f' {original_destination_index}')
No validation on number?

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +                len(playlist).
What if `source_index + number < dest_index`? Does this create problems? I'm just thinking of memcpy in C, where overlapping src and dest can create problems

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        tracks: A list of Track objects to populate the playlist. These will be
Instead of 'These will be the only tracks in the playlist', maybe say 'this function will remove all existing tracks in the playlist and replace them with `tracks`'

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        endpoint = Endpoints.BASE_URI
Should validate inputs

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST_IMAGES.replace('{playlist_id}',
% formatting

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        body = []
Do you think it's worth checking that the filename ends in .jpg? I feel like it could be a fairly common error where people accidentally use a .png or something

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST.replace('{playlist_id}', self._raw['id'])
% formatting

2020-06-01 01:27 UTC, Guptacos commented on spotifython/playlist.py
> +from copy import deepcopy
Standard library inputs should be at the top

2020-06-08 01:50 UTC, spenceryu commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST_TRACKS % self._raw['id']
nit: shouldn't this use .spotify_id()

2020-06-08 01:52 UTC, spenceryu requested changes

2020-06-08 01:52 UTC, spenceryu commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST % self._raw['id']
nit: shouldn't this use .spotify_id()

2020-06-08 01:52 UTC, spenceryu commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST % self._raw['id']
same

2020-06-08 01:52 UTC, spenceryu commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST_IMAGES % self._raw['id']
same

2020-06-08 01:52 UTC, spenceryu commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST_TRACKS % self._raw['id']
same

2020-06-08 01:52 UTC, spenceryu commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST_TRACKS % self._raw['id']
same

2020-06-08 01:52 UTC, spenceryu commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST_TRACKS % self._raw['id']
same

2020-06-08 01:52 UTC, spenceryu commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST_TRACKS % self._raw['id']
same

2020-06-08 01:52 UTC, spenceryu commented on spotifython/playlist.py
> +        endpoint += Endpoints.PLAYLIST_IMAGES % self._raw['id']
same

2020-06-08 15:12 UTC, Guptacos submitted a review, later dismissed

2020-06-08 15:29 UTC, merged