Track implementation
Guptacos/spotifython pull request #73
Opened 2020-06-03 14:19 UTC by Guptacos

2020-06-06 18:50 UTC, spenceryu commented on spotifython/endpoints.py
> +
do you think we should adopt the endpoint convention [CLASS] + 'endpointname' across all our endpoints in a future pr?

2020-06-06 18:50 UTC, spenceryu commented on spotifython/track.py
> +    """ The Track class. Use methods here to get information about a Track.
mention that it is tied to a spotify id?

2020-06-06 18:58 UTC, spenceryu requested changes

2020-06-06 18:58 UTC, spenceryu commented on spotifython/track.py
> +    # TODO: should init call self._update_fields()?
I think it makes sense to here, to front load the cost for initialization. We may have use cases that require the methods/field accessing of our classes to be more performant.

2020-06-06 18:58 UTC, spenceryu commented on spotifython/track.py
> +        # TODO: name this _raw or _info?
I think _raw, that's the convention we've been following elsewhere. It makes sense because it is the raw JSON.

2020-06-06 18:58 UTC, spenceryu commented on spotifython/track.py
> +    # TODO: is it bad for print to make api calls?
It doesn't make sense for print to have side effects/unexpected behavior. I'd argue that most of the use for print is either stdout/UI elements/logging, and this means we want the function to be able to work without network calls.

2020-06-06 18:58 UTC, spenceryu commented on spotifython/track.py
> +    # TODO: should include artists?
Don't think so.

2020-06-06 18:58 UTC, spenceryu commented on spotifython/track.py
> +    # Too long print?
I think that's ok, it's repr not str

2020-06-06 18:58 UTC, spenceryu commented on spotifython/track.py
> +        popular. This number is calculated by a Spotify algorithm.
A little ambiguous to say "calculated by a Spotify algorithm" - this might mean an algorithm that Spotify has published or something. How about "calculated in the Spotify API backend"?

2020-06-06 18:58 UTC, spenceryu commented on spotifython/track.py
> +        """ Get the Track's disc number (1 indexed)
Is there a good reason to use 1-indexed over 0-indexed? This library is provided to programmers, who (unless they're primarily MATLAB users) are likely to think of things in terms of 0-indexing.

2020-06-06 18:58 UTC, spenceryu commented on spotifython/track.py
> +    # TODO: maybe change this to a feature object?
I think that's a reasonable decision, in line with our principles of avoiding json/dict blobs

2020-06-06 18:58 UTC, spenceryu commented on spotifython/track.py
> +    # TODO: this is a fat response json... should we make an analysis object?
just like above, also yes

2020-06-07 02:48 UTC, rmannava commented on spotifython/endpoints.py
> +
i think they should be the categories in the web api reference but yeah

2020-06-07 13:13 UTC, Guptacos commented on spotifython/endpoints.py
> +
Yea let's leave as a future TODO

2020-06-08 15:51 UTC, Guptacos commented on spotifython/track.py
> +    """ The Track class. Use methods here to get information about a Track.
Mentioned in the file comment instead

2020-06-08 15:51 UTC, Guptacos commented on spotifython/track.py
> +    # TODO: should init call self._update_fields()?
I think this is a more underlying problem that we should address in a future commit. If we want to provide frontloadable objects that are more performant, we should offer that everywhere with a parameter (probably in the Session constructor) specifying that.

For now I think it's reasonable for classes to put off fetching until later

2020-06-08 15:51 UTC, Guptacos commented on spotifython/track.py
> +    # TODO: is it bad for print to make api calls?
Makes sense. I'll add a check in the constructor to make sure `name` is `in _raw`

2020-06-08 15:51 UTC, Guptacos commented on spotifython/track.py
> +        """ Get the Track's disc number (1 indexed)
I agree. However, track_number is also 1 indexed (I updated the docs). The only argument i could see for keeping 1 indexing is that is how you'd see it in any other Spotify interface you use; the first track in an album in numbered `1`.

Whichever we pick, the same indexing should be used in album.__getitem__

2020-06-08 15:51 UTC, Guptacos commented on spotifython/track.py
> +    # TODO: maybe change this to a feature object?
The only reason I'd be against this is that the feature obj is a flat json with 'featurename': 'value', and the value is dependent on the feature. Clients would have to look at the spotify docs anyway, unless we copy the docs directly into our own docs.

The only time I can think of people using the audio_features is for a data science type project, in which case a dict is a known (and easily usable) object for aggregation / parsing

```
{
  "danceability": 0.767,
  "energy": 0.392,
  "key": 1,
  "loudness": -11.996,
  "mode": 1,
  "speechiness": 0.0945,
  "acousticness": 0.154,
  "instrumentalness": 0.000398,
  "liveness": 0.108,
  "valence": 0.48,
  "tempo": 125.017,
  "type": "audio_features",
  "id": "4BsLwvaJOTOHDNg7xMpvrL",
  "uri": "spotify:track:4BsLwvaJOTOHDNg7xMpvrL",
  "track_href": "https://api.spotify.com/v1/tracks/4BsLwvaJOTOHDNg7xMpvrL",
  "analysis_url": "https://api.spotify.com/v1/audio-analysis/4BsLwvaJOTOHDNg7xMpvrL",
  "duration_ms": 153872,
  "time_signature": 4
}
```

2020-06-08 15:51 UTC, Guptacos commented on spotifython/track.py
> +    # TODO: this is a fat response json... should we make an analysis object?
We should discuss this in more detail, let's move it to the groupchat

2020-06-08 15:53 UTC, merged