Documentation
Guptacos/spotifython pull request #74
Opened 2020-06-03 14:59 UTC by Guptacos

Set up Sphinx and documentation generation

2020-06-06 19:01 UTC, spenceryu requested changes

2020-06-06 19:01 UTC, spenceryu commented on docs/source/intro.rst
> +``Spotifython`` is an object-oriented Python wrapper for the Spotify `web api
Is 'api' supposed to be lowercase or capitalized? It's an abbreviation so I'd presume it makes sense to use the uppercase veresion across the documentation.

2020-06-07 02:53 UTC, rmannava commented on docs/source/intro.rst
> +``Spotifython`` is an object-oriented Python wrapper for the Spotify `web api
same with JSON

2020-06-07 02:53 UTC, rmannava commented on docs/source/intro.rst
> +Despite these limitations, we feel that the library can help cover a large
feel -> believe? seems more professional to me

2020-06-07 14:12 UTC, merged