Album implementation
Guptacos/spotifython pull request #75
Opened 2020-06-05 13:17 UTC by Guptacos

2020-06-06 19:06 UTC, spenceryu requested changes

2020-06-06 19:06 UTC, spenceryu commented on spotifython/album.py
> +This class represents an Album object, which represents a Spotify album.
Tied to a spotify id

2020-06-06 19:06 UTC, spenceryu commented on spotifython/album.py
> +        The Album class does not currently support track relinking using market
We need to probably define track relinking somewhere in our documentation, so users do not have to search to find Spotify's definition. Maybe we could even provide a link to Spotify's documentation on track relinking in our description.

2020-06-06 19:06 UTC, spenceryu commented on spotifython/album.py
> +            One of:
We should standardize how we define our returns. Do you think the bulleted style below or a short paragraph is more appropriate? @rmannava as well

2020-06-06 19:06 UTC, spenceryu commented on spotifython/album.py
> +            List[dict]: a list of copyright objects as defined here:
Add a copyright object as an issue to solve in a future release? We also have to be conscious of the fact that any object model that we do not create a class for in our initial release may cause backwards incompatability. In that case, we'd be forced to create a new method that returns the class in the future, which is something we're trying to avoid doing.

2020-06-07 04:45 UTC, rmannava commented on spotifython/album.py
> +            One of:
id prefer the paragraph because its likely that there is some explanation to go with the returns, but i could be convinced

should also decide between List[Object] and "list of objects"

2020-06-07 04:45 UTC, rmannava commented on spotifython/album.py
> +                * sp.ALBUMS
should have an explanation here; not sure what the difference is between albums and compilation

2020-06-07 04:45 UTC, rmannava commented on spotifython/album.py
> +        self._artists = [Artist(self._session, art) for art in artists]
art -> artist?

2020-06-07 13:11 UTC, Guptacos commented on spotifython/album.py
> +        The Album class does not currently support track relinking using market
I agree. I think this should be a TODO for after we merge everything in and actually have central documentation

2020-06-07 13:11 UTC, Guptacos commented on spotifython/album.py
> +            One of:
I chose this format because it looks a lot better in the final sphinx rendered documentation. No one will really be looking directly at the source code, so this is better

2020-06-07 13:11 UTC, Guptacos commented on spotifython/album.py
> +            One of:
After all the code is merged in and the sphinx stuff is set up, we'll all have to modify our docstrings so that they render properly in the html

2020-06-07 13:11 UTC, Guptacos commented on spotifython/album.py
> +                * sp.ALBUMS
These are music terms, not Spotify terms - do you think we should still define them?
album = new content released by artist
compilation = collection of already released music by an artist, such as "beatle's greatest hits"

2020-06-07 13:11 UTC, Guptacos commented on spotifython/album.py
> +            List[dict]: a list of copyright objects as defined here:
I was a bit conflicted on this. I agree that we should probably define objects for everything. But here, a "copyright object" is a dict with only 2 keys:
```
{
    "text": "(P) 2000 Sony Music Entertainment Inc.",
    "type": "P"
}
```
Do you think this still merits its own object?

2020-06-07 20:01 UTC, Guptacos commented on spotifython/album.py
> +            List[dict]: a list of copyright objects as defined here:
Make copyright object

2020-06-08 16:23 UTC, merged