Add complex Player example
Guptacos/spotifython pull request #76
Opened 2020-06-05 15:05 UTC by Guptacos

Create example that shows how to embed Spotifython into an existing
application to display playback.

Example creates a tkinter GUI, and displays current song / artist name,
along with album art. Allows user to click buttons to play, pause, skip,
and go to previous song.

2020-06-06 19:08 UTC, spenceryu requested changes

2020-06-06 19:08 UTC, spenceryu commented on examples/player_control.py
> +    TODO: put reauth link
Should the TODOs here be fixed in a future release?

2020-06-06 19:10 UTC, spenceryu commented on examples/player_control.py
> +session = sp.Session(os.environ['TOKEN'])
Maybe add a comment that this is on the user to set?

2020-06-07 02:37 UTC, Guptacos commented on examples/player_control.py
> +    TODO: put reauth link
I forgot to fix this, I'll take care of it

2020-06-07 12:45 UTC, merged