User data
Guptacos/spotifython pull request #80
Opened 2020-06-08 19:30 UTC by Guptacos

Add getter methods to the User class for various user information

2020-06-08 19:31 UTC, Guptacos commented
The images branch must be merged before this one

2020-06-09 00:32 UTC, rmannava requested changes

2020-06-09 00:32 UTC, rmannava commented on spotifython/user.py
> +        * followers: unsupported by Spotify, see https://developer.spotify.com/documentation/web-api/reference/object-model/#followers-object
google style guide says to put the url on its own line of its too long, might not need the pylint disable

2020-06-09 00:32 UTC, rmannava commented on spotifython/user.py
> +        self._raw = {**self._raw, **response_json}
would self._raw.update(response_json) do the same thing?

2020-06-09 00:32 UTC, rmannava commented on spotifython/user.py
> +        self._raw = {**self._raw, **other._raw}
same as above

2020-06-09 02:00 UTC, spenceryu commented on spotifython/user.py
> +        self._raw = {**self._raw, **response_json}
I use this magic method across a lot of my code too. If we change this, it should be a separate PR

2020-06-09 02:01 UTC, spenceryu submitted a review, later dismissed

2020-06-09 13:39 UTC, Guptacos commented on spotifython/user.py
> +        self._raw = {**self._raw, **response_json}
Yea it does see the groupchat

2020-06-09 13:40 UTC, Guptacos commented on spotifython/user.py
> +        * followers: unsupported by Spotify, see https://developer.spotify.com/documentation/web-api/reference/object-model/#followers-object
It's too long even on its own line; this way at least it renders nicely with sphinx

2020-06-09 13:44 UTC, merged