Organize the endpoints.py file
Guptacos/spotifython pull request #91
Opened 2020-06-11 16:07 UTC by Guptacos

2020-06-13 22:46 UTC, spenceryu submitted a review, later dismissed
You should probably update the PR to note that playlist URIs are also fixed here.

2020-06-14 00:27 UTC, rmannava requested changes

2020-06-14 00:27 UTC, rmannava commented on spotifython/endpoints.py
> +    ARTIST_TOP_TRACKS = ARTIST_GET_DATA + '/top-tracks'
can we remove 'GET' from all the endpoints? not every endpoint has it when it should like top tracks, and it would be cleaner to just remove every get

2020-06-14 00:27 UTC, rmannava commented on spotifython/endpoints.py
> +    SEARCH_GET_PLAYLIST = 'playlists/%s'
user and playlist are repeated endpoints

2020-07-20 02:56 UTC, spenceryu commented on spotifython/endpoints.py
> +    SEARCH_GET_PLAYLIST = 'playlists/%s'
Not coupling these two methods is easier for us to maintain in the interest of future maintainability.

2020-07-20 21:50 UTC, rmannava approved these changes

2020-07-20 21:50 UTC, merged