Testing with mocks for artist
Guptacos/spotifython pull request #98
Opened 2020-06-15 07:35 UTC by spenceryu

2020-06-20 19:11 UTC, rmannava requested changes

2020-06-20 19:11 UTC, rmannava commented on spotifython/artist.py
> +               search_limit=50,
i thought we wanted defaults to be unlimited

2020-06-21 17:27 UTC, spenceryu commented on spotifython/artist.py
> +               search_limit=50,
Yeah, that is my bad. One problem with using a loop `for offset in range(0, num_to_request, page_size):` in paginate_get though is there is no way to keep going to unlimited items, instead of using a while loop.

2020-06-27 18:40 UTC, rmannava approved these changes

2020-07-09 01:05 UTC, merged